name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - name: Build JSDoc
        run: npm run build:docs
      - name: Copy CNAME
        run: cp CNAME docs/out/
      - name: Deploy
        uses: s0/git-publish-subdir-action@2.4.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_EMPTY_COMMITS: true
